services:
  app:
    image: toyama4649/kirameki-php-cli:latest
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: user
        target: /root
volumes:
  user:
